name: alma

services:
    api:
        build: .
        container_name: alma-api
        volumes:
            - ./Databases:/App/Databases
            - ./DataProtection-Keys:/root/.aspnet/DataProtection-Keys
        ports:
            - 5123:5123
        environment:
            - ASPNETCORE_URLS=http://*:5123
        healthcheck:
            test: "wget --no-verbose --tries=1 --spider http://localhost:5123 || exit 1"
            start_period: 10s
            start_interval: 1s
        restart: unless-stopped
