name: alma

services:
    api:
        build: .
        container_name: alma-api
        ports:
            - 5123:5123
        depends_on:
            mongodb:
                condition: service_healthy
        environment:
            - ASPNETCORE_URLS=${ASPNETCORE_URLS:-http://*:5123}
            - MONGODB_HOST=mongodb
            - MONGODB_PORT=${MONGODB_PORT:-27017}
            - MONGODB_DBNAME=${MONGODB_DBNAME:-alma}
            - MONGODB_USERNAME=${MONGODB_USERNAME:-alma}
            - MONGODB_PASSWORD=${MONGODB_PASSWORD:-password}
        healthcheck:
            test: "wget --no-verbose --tries=1 --spider http://localhost:5123 || exit 1"
            start_period: 10s
            start_interval: 1s
        restart: unless-stopped

    mongodb:
        image: mongo:8-noble
        container_name: alma-mongodb
        volumes:
            - ./mongodb-entrypoint.sh:/docker-entrypoint-initdb.d/db-entrypoint.sh
            - ./mongodb-data:/data/db
        expose:
            - ${MONGODB_PORT:-27017}
        environment:
            - MONGODB_PORT=${MONGODB_PORT:-27017}
            - MONGO_INITDB_ROOT_USERNAME=${MONGODB_ROOT_USERNAME:-root}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD:-password}
            - MONGODB_DBNAME=${MONGODB_DBNAME:-alma}
            - MONGODB_USERNAME=${MONGODB_USERNAME:-alma}
            - MONGODB_PASSWORD=${MONGODB_PASSWORD:-password}
        healthcheck:
            test: 'echo ''db.runCommand("ping").ok'' | mongosh mongodb://${MONGODB_USERNAME:-alma}:${MONGODB_PASSWORD:-password}@localhost:${MONGODB_PORT:-27017}/?authSource=${MONGODB_DBNAME:-alma} --quiet'
            start_period: 10s
            start_interval: 1s
        restart: unless-stopped
